### ISSUE TITLE
Aliases management

### ISSUE THREAD

**Issue by teadur** [reallyenglish/ansible-role-postfix#23]
As i understand currently the role doesnot manage /etc/aliases.
If i define custom alias_maps/alias_database and use roles hash_table feature to manage aliases.hash
First run is okey all the defined data works as expceted but once i  modify the alises table variable the db 
doesnot get updated, i have to run postmap on it by hand to get changes applied.

Am i using the role incorrectly or i have stumbled on a bug ?

**Comment by trombik** [comment]
thanks for reporting the issue.

yes, you have.

**Comment by trombik** [comment]
would you post your playbook (if it's too long, please use gist)? if it is not possible, please post

* variables that start with `postfix_` in your playbook or `group_vars`
* OS platform name

**Comment by trombik** [comment]
this tree should fix the issue: https://github.com/reallyenglish/ansible-role-postfix/tree/remove_makefile

**Comment by trombik** [comment]
releases as 1.1.0

**Comment by teadur** [comment]
Thank you for quick fix, sadly i was really busy last week and havent had time to test the fixed version yet, but will give it a try soonish and will open the issue again if problem persist.
